title: Armani-Write-Ups
description: "Bienvenidos a mi blog!!! Subiré writeups personales de máquinas HTB"
author:
  name: "Armando"
  email: "foxtrot_mike_sierra@proton.me"
  url: "https://github.com/armani252/armani252.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Armani"
year : "2024"
